server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:rasmoodb
    driver-class-name: org.h2.Driver
    username: rasmoo
    password: rasmoo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2